### ISSUE TITLE
Bukan FB Hack

### ISSUE THREAD

**Issue by hansputera** [pashayogi/SETAN#21]
melihat dan mengidentifikasi kodenya itu variabel 
`pz2 = a["first_name"] + '123'`

Ini cuman get statistic user doang.

**Comment by hansputera** [comment]
Tapi okelah mantap niatnya

**Comment by topan507** [comment]
Ini tentang apa..? 🤔🤔

**Comment by hansputera** [comment]
> Ini tentang apa..? 🤔🤔

Statistics user doang sih mainan OAuth2 Saja

**Comment by Cyber2f08** [comment]
_wwooooh_

**Comment by pashayogi** [comment]
kata sapa bukan hack fb? situ kalo gak ngerti jangan asal ngomong gan itu scnya gak gw encode jadi lu bisa liat ada keylogernya apa enggak sekia. TERIMAKASIH!

**Comment by hansputera** [comment]
![Screenshot_2021-04-24-07-39-49-94](https://user-images.githubusercontent.com/47862061/115941469-a813fd80-a4cf-11eb-9517-5989bb58c8c5.png)
![Screenshot_2021-04-24-07-39-59-96](https://user-images.githubusercontent.com/47862061/115941472-ab0eee00-a4cf-11eb-894a-a5325d30c8c2.png)

Ini gan, variabel pz1 itu `first_name` dan ditambah `123`.

**Comment by hansputera** [comment]
Login, dapatin members group, dapatin friends itu menggunakan Graph API facebook authenticationnya pake access token.

**Comment by yrifl** [comment]
> ![Screenshot_2021-04-24-07-39-49-94](https://user-images.githubusercontent.com/47862061/115941469-a813fd80-a4cf-11eb-9517-5989bb58c8c5.png)
> ![Screenshot_2021-04-24-07-39-59-96](https://user-images.githubusercontent.com/47862061/115941472-ab0eee00-a4cf-11eb-894a-a5325d30c8c2.png)
> 
> Ini gan, variabel pz1 itu `first_name` dan ditambah `123`.

Bolehkah saya melihat full codenya?

**Comment by hansputera** [comment]
> > ![Screenshot_2021-04-24-07-39-49-94](https://user-images.githubusercontent.com/47862061/115941469-a813fd80-a4cf-11eb-9517-5989bb58c8c5.png)
> > ![Screenshot_2021-04-24-07-39-59-96](https://user-images.githubusercontent.com/47862061/115941472-ab0eee00-a4cf-11eb-894a-a5325d30c8c2.png)
> > Ini gan, variabel pz1 itu `first_name` dan ditambah `123`.
> 
> Bolehkah saya melihat full codenya?

Tinggal liat repositoryny klik filenya.

**Comment by pashayogi** [comment]
itu semacam brute froce paham gak dek? mencocok sandi si target kalo salah gagal pahami dulu yak dek

**Comment by hansputera** [comment]
Sudah gan, tapi keberhasilan dapatnya kecil karena hanya menebak nebak password saja.

**Comment by bokunodev** [comment]
> Login, dapatin members group, dapatin friends itu menggunakan Graph API facebook authenticationnya pake access token.

dan access token nya di umbar2, silakan pake mumpung gratis. kapan lagi dapen fb api key gratis.

**Comment by hansputera** [comment]
> > Login, dapatin members group, dapatin friends itu menggunakan Graph API facebook authenticationnya pake access token.
> 
> dan access token nya di umbar2, silakan pake mumpung gratis. kapan lagi dapen fb api key gratis.

wkwkwkwk
